//DAY 2 ASSIGNMENT 1                                    


 
>>> # STRING METHODS IN PYTHON
>>> str="Lets Upgrade python"
>>> print(str.upper())
LETS UPGRADE PYTHON
>>> print(str.islower())
False
>>> print(str.swapcase())
lETS uPGRADE PYTHON
>>> print(str.endswith("python"))
True
>>> print(str.replace("python","Java"))
Lets Upgrade Java
>>> print(str.capitalize())
Lets upgrade python
 
 
 
>>> # FUNCTIONS OF DICTIONARY IN PYTHON
>>> dict={1:"one",2:"two",3:"three",4:"four",5:"five"}
>>> print(dict.copy())
{1: 'one', 2: 'two', 3: 'three', 4: 'four', 5: 'five'}
>>> print(dict.keys())
dict_keys([1, 2, 3, 4, 5])
>>> print(dict.get(2))
two
>>> print(dict.items())
dict_items([(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')])
>>> print(dict.values())
dict_values(['one', 'two', 'three', 'four', 'five'])
>>> print(dict.clear())
None




>>> #FUNCTIONS OF LIST OBJECT IN PYTHON
>>> lst=[1,6,9.2,"sam",5,3.5,8,"ram"]
>>> print(lst.append("latha"))
None
>>> print(lst.count(1))
1
>>> print(lst.index(3.5))
5
>>> print(lst.remove(8))
None
>>> print(lst.reverse())
None
>>> print(lst.count(5))
1
>>> print(lst.copy())
['latha', 'ram', 3.5, 5, 'sam', 9.2, 6, 1]

